//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Input/FoodDeliveryInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Input/FoodDeliveryInputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @FoodDeliveryInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @FoodDeliveryInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""FoodDeliveryInputActions"",
    ""maps"": [
        {
            ""name"": ""FoodDelivery"",
            ""id"": ""190cf7c2-d0fc-451f-bb93-78b5845a9b22"",
            ""actions"": [
                {
                    ""name"": ""ToggleEventLogs"",
                    ""type"": ""Button"",
                    ""id"": ""3ca6bc4c-689d-4c5f-88f7-11af22e2b0b2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d7bfa436-8a85-4f72-925b-762d562c16ee"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleEventLogs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // FoodDelivery
        m_FoodDelivery = asset.FindActionMap("FoodDelivery", throwIfNotFound: true);
        m_FoodDelivery_ToggleEventLogs = m_FoodDelivery.FindAction("ToggleEventLogs", throwIfNotFound: true);
    }

    ~@FoodDeliveryInputActions()
    {
        UnityEngine.Debug.Assert(!m_FoodDelivery.enabled, "This will cause a leak and performance issues, FoodDeliveryInputActions.FoodDelivery.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // FoodDelivery
    private readonly InputActionMap m_FoodDelivery;
    private List<IFoodDeliveryActions> m_FoodDeliveryActionsCallbackInterfaces = new List<IFoodDeliveryActions>();
    private readonly InputAction m_FoodDelivery_ToggleEventLogs;
    /// <summary>
    /// Provides access to input actions defined in input action map "FoodDelivery".
    /// </summary>
    public struct FoodDeliveryActions
    {
        private @FoodDeliveryInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public FoodDeliveryActions(@FoodDeliveryInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "FoodDelivery/ToggleEventLogs".
        /// </summary>
        public InputAction @ToggleEventLogs => m_Wrapper.m_FoodDelivery_ToggleEventLogs;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_FoodDelivery; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="FoodDeliveryActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(FoodDeliveryActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="FoodDeliveryActions" />
        public void AddCallbacks(IFoodDeliveryActions instance)
        {
            if (instance == null || m_Wrapper.m_FoodDeliveryActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FoodDeliveryActionsCallbackInterfaces.Add(instance);
            @ToggleEventLogs.started += instance.OnToggleEventLogs;
            @ToggleEventLogs.performed += instance.OnToggleEventLogs;
            @ToggleEventLogs.canceled += instance.OnToggleEventLogs;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="FoodDeliveryActions" />
        private void UnregisterCallbacks(IFoodDeliveryActions instance)
        {
            @ToggleEventLogs.started -= instance.OnToggleEventLogs;
            @ToggleEventLogs.performed -= instance.OnToggleEventLogs;
            @ToggleEventLogs.canceled -= instance.OnToggleEventLogs;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="FoodDeliveryActions.UnregisterCallbacks(IFoodDeliveryActions)" />.
        /// </summary>
        /// <seealso cref="FoodDeliveryActions.UnregisterCallbacks(IFoodDeliveryActions)" />
        public void RemoveCallbacks(IFoodDeliveryActions instance)
        {
            if (m_Wrapper.m_FoodDeliveryActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="FoodDeliveryActions.AddCallbacks(IFoodDeliveryActions)" />
        /// <seealso cref="FoodDeliveryActions.RemoveCallbacks(IFoodDeliveryActions)" />
        /// <seealso cref="FoodDeliveryActions.UnregisterCallbacks(IFoodDeliveryActions)" />
        public void SetCallbacks(IFoodDeliveryActions instance)
        {
            foreach (var item in m_Wrapper.m_FoodDeliveryActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FoodDeliveryActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="FoodDeliveryActions" /> instance referencing this action map.
    /// </summary>
    public FoodDeliveryActions @FoodDelivery => new FoodDeliveryActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "FoodDelivery" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="FoodDeliveryActions.AddCallbacks(IFoodDeliveryActions)" />
    /// <seealso cref="FoodDeliveryActions.RemoveCallbacks(IFoodDeliveryActions)" />
    public interface IFoodDeliveryActions
    {
        /// <summary>
        /// Method invoked when associated input action "ToggleEventLogs" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleEventLogs(InputAction.CallbackContext context);
    }
}
